-- Tworzenie sekwencji dla każdej tabeli
CREATE SEQUENCE country_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE currency_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE location_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE flags_seq START WITH 1 INCREMENT BY 1;

-- Tworzenie tabeli country
CREATE TABLE country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    common VARCHAR(255),
    official VARCHAR(255),
    independent BOOLEAN,
    un_member BOOLEAN,
    region VARCHAR(255),
    subregion VARCHAR(255),
    landlocked BOOLEAN,
    area DOUBLE,
    population INT,
);

-- Tworzenie tabeli currency
CREATE TABLE currency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255),
    symbol VARCHAR(255),
    country_id BIGINT,
    FOREIGN KEY (country_id) REFERENCES country(id)
);

-- Tworzenie tabeli location
CREATE TABLE location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255),
    country_id BIGINT,
    is_capital BOOLEAN,
    FOREIGN KEY (country_id) REFERENCES country(id)
);

-- Tworzenie tabeli flags
CREATE TABLE flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    png VARCHAR(255),
    alt VARCHAR(1000),
    country_id BIGINT,
    FOREIGN KEY (country_id) REFERENCES country(id)
);
